# Generated by Django 4.2.7 on 2023-12-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_films_director_alter_films_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.directors'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RelFilmsActors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actors')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.films')),
            ],
        ),
    ]
