# Generated by Django 4.2.7 on 2023-12-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_films_director_relfilmsactors'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelFilmsActors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actors')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.films')),
            ],
        ),
    ]
