# Generated by Django 4.2.7 on 2023-12-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_films_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
