# Generated by Django 4.2.7 on 2023-12-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_films_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterUniqueTogether(
            name='relfilmsactors',
            unique_together={('film', 'actor')},
        ),
        migrations.CreateModel(
            name='RelFilmsGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.films')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genres')),
            ],
            options={
                'unique_together': {('film', 'genre')},
            },
        ),
    ]
